#!/bin/bash
#
#SBATCH --job-name=xrt
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=2G
#SBATCH --time=10:00:00
#SBATCH --output=%x_%A_%a.out
#SBATCH --error=%x_%A_%a.err
#SBATCH --array=0-3

pixi run python sims/hello_world/runner.py config_$SLURM_ARRAY_TASK_ID.toml /nsls2/data3/projects/next_iiia_hrd/xrt_output/20250116/${SLURM_ARRAY_JOB_ID}-$SLURM_ARRAY_TASK_ID.h5 --cache-rate=1000
