#!/bin/bash
#
#SBATCH --job-name=xrt
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=2G
#SBATCH --time=10:00:00
#SBATCH --output=output/%x_%A_%a.out
#SBATCH --error=output/%x_%A_%a.err
#SBATCH --array=0-3

mkdir -p output

pixi run -e xrt --frozen python ../hello_world/runner.py configs/config_$SLURM_ARRAY_TASK_ID.toml /nsls2/data3/projects/next_iiia_hrd/xrt_output/$(date '+%Y%m%d')/${SLURM_ARRAY_JOB_ID}-$SLURM_ARRAY_TASK_ID.h5 --cache-rate=200
